name: Run main.py every 5 minutes

on:
  schedule:
    - cron: "*/4 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Set up Python 3.x
        uses: actions/setup-python@v5  
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create JSON file from secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > credentials.json

      - name: Run main.py
        run: python main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          STOCK: ${{ secrets.STOCK }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

      - name: Clean up
        run: rm credentials.json
