name: Run main.py every 5 minutes

on:
  schedule:
    - cron: "*/4 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  

      - name: Set up Python 3.x
        uses: actions/setup-python@v5  
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create JSON file from secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}" | base64 --decode > credentials.json

      - name: Ensure last_sent_messages.json exists
        run: |
          if [ ! -f last_sent_messages.json ]; then
            echo '{}' > last_sent_messages.json
          fi

      - name: Restore last_sent_messages.json from cache
        id: cache-last-sent
        uses: actions/cache@v3
        with:
          path: last_sent_messages.json
          key: last-sent-messages-cache-${{ github.run_id }}

      - name: Run main.py
        run: python main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          STOCK: ${{ secrets.STOCK }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

      - name: Update last_sent_messages.json cache
        uses: actions/cache@v3
        with:
          path: last_sent_messages.json
          key: last-sent-messages-cache-${{ github.run_id }}

      - name: Clean up
        run: rm credentials.json
